Books/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$',views.book_list,name='book_list'),
    url(r'^datatable$',views.dataTable,name='datatable'),
    url(r'^create/$', views.book_create, name='book_create'),
    url(r'^(?P<pk>\d+)/book_update/$', views.book_update, name='book_update'),
    url(r'^(?P<pk>\d+)/book_delete/$', views.book_delete, name='book_delete'),



]

ajax/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from rest_framework import routers
from Books.views import BookViewSet

router=routers.DefaultRouter()
router.register(r'books-api',BookViewSet)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'ajax/',include('contact.urls')),
    url(r'books/',include('Books.urls')),
    url(r'api/',include(router.urls)),

]

contact/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
    url(r'^$',views.create,name='create'),
    url(r'saveContact$',views.saveContact,name='saveContact'),
]

Books/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Book(models.Model):
    HARDCOVER = 1
    PAPERBACK = 2
    EBOOK = 3
    BOOK_TYPES = (
        (HARDCOVER, 'Hardcover'),
        (PAPERBACK, 'Paperback'),
        (EBOOK, 'E-book'),
    )
    title = models.CharField(max_length=50)
    publication_date = models.DateField(null=True)
    author = models.CharField(max_length=30, blank=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    pages = models.IntegerField(blank=True, null=True)
    book_type = models.PositiveSmallIntegerField(choices=BOOK_TYPES)

    def __str__(self):
        return self.title+" by "+self.author

    @classmethod
    def __all__(cls):
        return cls._meta.fields

contact/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# Create your models here.
class Contact(models.Model):
    name=models.CharField(max_length=25,blank=False)
    email=models.CharField(max_length=30,blank=False)
    subject=models.CharField(max_length=50,blank=False)

    def __str__(self):
        return self.name

Books/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'publication_date', 'author', 'price', 'pages', 'book_type', )

contact/forms.py
from django.forms import ModelForm
from .models import Contact


class ContactForm(ModelForm):

    class Meta:
        model=Contact
        fields= ('name','email','subject')

Books/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render,get_object_or_404
from .models import Book
from django.http import JsonResponse
from .forms import BookForm
from django.template.loader import render_to_string
from rest_framework import viewsets
from  .serializers import BookSerializer


def book_list(request):
    books = Book.objects.all()
    return render(request, 'books/book_list.html', {'book_list': books})


def save_book_form(request,form, templete_name):
    data = dict()
    if request.method == 'POST':

        if form.is_valid():
            form.save()
            data['form_is_valid']=True
            books=Book.objects.all()
            data['html_book_list']=render_to_string('books/includes/partial_book_list.html',
                                                    {
                                                        'book_list': books
                                                    })
        else:
            data['form_is_valid']=False

    context={
        'form':form,
    }
    data['html_form']=render_to_string(templete_name,
                               context=context,
                               request=request
                               )
    return JsonResponse(data)


def book_create(request):
    if request.method=='POST':
        form=BookForm(request.POST)
    else:
        form=BookForm()
    return save_book_form(request,form,'books/includes/partial_book_create.html')


def book_update(request,pk):
    book=get_object_or_404(Book,pk=pk)
    if request.method=='POST':
        form=BookForm(request.POST,instance=book)
    else:
        form=BookForm(instance=book)
    return save_book_form(request,form,'books/includes/partial_book_update.html')


def book_delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    data = dict()
    if request.method == 'POST':
        book.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        books = Book.objects.all()
        data['html_book_list'] = render_to_string('books/includes/partial_book_list.html', {
            'book_list': books
        })
    else:
        context = {'book': book}
        data['html_form'] = render_to_string('books/includes/partial_book_delete.html',
            context,
            request=request,
        )
    return JsonResponse(data)


class BookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all().order_by('title')
    serializer_class = BookSerializer


def dataTable(request):
    return render(request,'books/book-datatable.html')

contact/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .models import Contact
from .forms import ContactForm
from django.http import JsonResponse
# Create your views here.


def create(request):

    form=ContactForm()
    return render(request,'create.html',{'form':form})


def saveContact(request):
    data={}
    if request.method == 'POST':
        form=ContactForm(request.POST)
        if form.is_valid():
            form.save()
            data = {
                'msg': 'Form submitted Successfully'
            }
        else:
            data = {
                'msg': 'Please fill up all the data!'
            }

    return JsonResponse(data)

templates/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bookstore</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
{#    {% include 'includes/header.html' %}#}
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    {% block javascript %}
        <script src="{% static 'book.js' %}"></script>
    {% endblock %}
  </body>
</html>

templates/books/book-datatable.html
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.css">
<link rel="stylesheet" href="//cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css">

<div class="container">
<div class="row">
<div class="col-sm-12">
<table id="albums" class="table table-striped table-bordered" style="width:100%" data-server-side="true" data-ajax="/api/books-api/?format=datatables">
<thead>
<tr>
<th data-data="title">title</th>
<th data-data="publication_date">publication date</th>
<th data-data="author">author</th>
<th data-data="pages">pages</th>
<th data-data="price">price</th>
<th data-data="book_type">book_type</th>
</tr>
</thead>
</table>
</div>
</div>
</div>
<script src="//code.jquery.com/jquery-1.12.4.js"></script>
<script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
<script src="//cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>
<script>
$(document).ready(function() {
$('#albums').DataTable();
});
</script>

templates/books/book_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <h1 class="page-header">Books</h1>
  <p class="page-header"><a href="{% url 'datatable' %}">Server side datatable</a></p>
    <p>
    <button type="button"
            data-url="{% url 'book_create' %}"
            class="btn btn-primary js-create-book">
      <span class="glyphicon glyphicon-plus"></span>
      New book
    </button>
  </p>

  <table class="table" id="book-table">
    <thead>
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Author</th>
        <th>Type</th>
        <th>Publication date</th>
        <th>Pages</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
        {% include 'books/includes/partial_book_list.html' %}
    </tbody>
  </table>
    <!-- THE MODAL WE WILL BE USING -->
  <div class="modal fade" id="modal-book">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
  </div>
{% endblock %}

templates/books/includes/partial_book_create.html
{% load widget_tweaks %}

<form method="post" action="{% url 'book_create' %}" class="js-book-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a new book</h4>
  </div>
  <div class="modal-body">
    {% for field in form %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
    {% endfor %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create book</button>
  </div>
</form>

templates/books/includes/partial_book_delete.html
<form method="post" action="{% url 'book_delete' book.id %}" class="js-book-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm book deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the book <strong>{{ book.title }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete book</button>
  </div>
</form>

templates/books/includes/partial_book_form.html
{% load widget_tweaks %}

{% for field in form %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <p class="help-block">{{ error }}</p>
        {% endfor %}
      </div>
{% endfor %}

templates/books/includes/partial_book_list.html
{% for book in book_list %}
        <tr>
          <td>{{ book.id }}</td>
          <td>{{ book.title }}</td>
          <td>{{ book.author }}</td>
          <td>{{ book.get_book_type_display }}</td>
          <td>{{ book.publication_date }}</td>
          <td>{{ book.pages }}</td>
          <td>{{ book.price }}</td>
        <td>
            <button type="button"
              class="btn btn-warning btn-sm js-update-book"
              data-url="{% url 'book_update' book.id %}">
        <span class="glyphicon glyphicon-pencil"></span> Edit
      </button>
            <button type="button"
              class="btn btn-danger btn-sm js-delete-book"
              data-url="{% url 'book_delete' book.id %}">
        <span class="glyphicon glyphicon-trash"></span> Delete
      </button>
        </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="7" class="text-center bg-warning">No book</td>
        </tr>
{% endfor %}

templates/books/includes/partial_book_update.html
<form method="post" action="{% url 'book_update' form.instance.pk %}" class="js-book-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Update book</h4>
  </div>
  <div class="modal-body">
    {% include 'books/includes/partial_book_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update book</button>
  </div>
</form>

templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

input[type=text], select, textarea {
    width: 100%;
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    margin-top: 6px;
    margin-bottom: 16px;
    resize: vertical;
}

button {
    background-color: #4CAF50;
    color: white;
    padding: 12px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

button:hover {
    background-color: #45a049;
}

.container {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
}
</style>
</head>
<body>
<form method="post" id="myForm" js-form-url="{% url 'saveContact' %}" onsubmit="ajaxReq()">
    {% csrf_token %}
    {{ form.as_p }}
    <div id="loader" hidden>Submitting...</div>
    <div id="success" hidden>Form submitted successfully</div>
    <br>
    <button onclick="ajaxReq()" type="button">Submit</button>
  </form>

<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
<script>
    function ajaxReq() {

       var form=$('#myForm')
        var div=$('#loader')
        div.show()
       var data=form.serializeArray()
        $.ajax({
            url:form.attr('js-form-url'),
            data:form.serialize(),
            dataType: 'json',
            method: 'post',
            success:function (data) {

                    console.log(data)
                    div.html(data.msg)
                form=form.reset


            }
        })
        console.log(data)
    }
</script>

</body>
</html>